{
  "apiVersion": 1,
  "datasources": [
    {
      "name": "prometheus",
      "type": "prometheus",
      "access": "direct",
      "orgId": 1,
      "url": "http://prometheus-service.monitoring.svc:8080",
      "isDefault": true,
      "version": 1,
      "editable": false
    }
  ]
}